export { default as Header } from './header/Header'
export { default as Klasemen } from './klasemen/Klasemen'
export { default as Kompetisi } from './kompetisi/Kompetisi'
export { default as Kontingen } from './kontingen/Kontingen'
export { default as PressRelease } from './pressRelease/PressRelease'
export { default as MedalTable} from './medalTable/MedalTable'
export { default as Olahraga } from './olahraga/Olahraga'
export { default as Seni } from './seni/Seni'
export { default as JadwalList } from './jadwalList/JadwalList'