export { default as Article } from './article/Article'
export { default as Article2 } from './article/Article2'
export { default as Department } from './department/Department'
export { default as Navbar } from './navbar/Navbar'
export { default as Slider } from './slider/Slider'
export { default as ButtonSlider } from './buttonSlider/ButtonSlider'
export { default as Medals } from './medals/Medals'
export { default as List} from './list/List'
export { default as H2H } from './h2h/H2H'
export { default as Jadwal } from './jadwal/Jadwal'
export { default as Participant } from './participant/Participant'
export { default as MatchResult } from './matchResult/MatchResult'
export { default as MatchSquad } from './matchSquad/MatchSquad'
export { default as PressReleaseCard } from './pressReleaseCard/PressReleaseCard'

export { default as NavbarAdmin } from './navbar/NavbarAdmin'
export { default as TableActions } from './spiritTable/TableActions'
export { default as TableDepartment } from './spiritTable/TableDepartment'
export { default as TableSport } from './spiritTable/TableSport'
export { default as TableAthlete } from './spiritTable/TableAthlete'
export { default as TableSportTeam } from './spiritTable/TableSportTeam'
export { default as TableMatch } from './spiritTable/TableMatch'
