GET http://localhost:8000/api/admins

###
GET http://localhost:8000/api/admins/6379016e17cd935191d075a9

###
POST http://localhost:8000/api/register
Content-Type: application/json

{
    "name": "spirit",
    "nim": "spirit",
    "department": "https://i.ibb.co/sQDzVhp/g1.png",
    "batch": "1",
    "email": "super_admin@spirit.com",
    "password": "1",
    "is_admin": true
}

###
POST http://localhost:8000/api/login
Content-Type: application/json

{
    "email": "bebekgorengs",
    "password": "2"
}

###
PATCH http://localhost:8000/api/admins/63787d7e4bd90f3636cc3f89
Content-Type: application/json

{
    "athletes_list": []
}

###
DELETE  http://localhost:8000/api/admins/63786f28c1c12eec1dceccf5
Content-Type: application/json