GET http://localhost:8000/api/matchs

###
GET http://localhost:8000/api/matchs/637e643e7c00f69fd8e0c62f



###
POST http://localhost:8000/api/matchs
Content-Type: application/json

{
    "sport_name": "s1",
    "dept_name1": "d1",
    "dept_name2": "d2",
    "dept_image1": "https://i.ibb.co/S3VmDzC/tes3.png",
    "dept_image2": "https://i.ibb.co/S3VmDzC/tes3.png",
    "location": "Gymnasium t1",
    "is_finished": false,
    "score_result": [1, 2],
    "time": "18:00",
    "day": "Senin",
    "date": "26 Oktober 2022"
}

###
PATCH http://localhost:8000/api/matchs/637ea11432d5a739e9712d14
Content-Type: application/json

{
    "is_finished": true
}

###
DELETE  http://localhost:8000/api/matchs/63791889503f1e53a5a22dc9
Content-Type: application/json