GET http://localhost:8000/sport-teams

###
GET http://localhost:8000/sport-teams/63786ec7c1c12eec1dceccf2

###
POST http://localhost:8000/sport-teams
Content-Type: application/json

{
    "department": "Biologi",
    "sport_type": "Futsal"
}

###
PATCH http://localhost:8000/sport-teams/6378fc9b17cd935191d07588
Content-Type: application/json

{
    "department": "Statistika",
    "sport_type": "Sepak Bola"
}

###
DELETE  http://localhost:8000/sport-teams/6378cdf27054e16c579b5f9a
Content-Type: application/json