export { default as Article } from './article/Article'
export { default as Article2 } from './article/Article2'
export { default as Department } from './department/Department'
export { default as Navbar } from './navbar/Navbar'
export { default as Slider } from './slider/Slider'
export { default as ButtonSlider } from './buttonSlider/ButtonSlider'
export { default as Medals } from './medals/Medals'
export { default as KometisiList} from './kompetisiList/KompetisiList'
export { default as H2H } from './h2h/H2H'
